stateDiagram-v2
    [*] --> BETTING
    
    state BETTING {
        [*] --> SelectRacer
        SelectRacer --> PlaceBet: Click Racer
        PlaceBet --> RACING: Bet Placed
    }
    
    state RACING {
        [*] --> Countdown
        Countdown --> RaceActive: GO!
        RaceActive --> RaceFinished: Winner Crosses Line
    }
    
    state FINISHED {
        [*] --> ShowResults
        ShowResults --> UpdateBalance: Win/Loss Calc
        UpdateBalance --> NextRound: Click Next
    }
    
    NextRound --> BETTING: New Round
